debug.log
package-lock.json
package.json
src/App.css
src/App.js

run npm install --save bootstrap
before npm start

added bootstrap

---

debug.log
src/components/Game/Game.js
src/components/Game/games.json

- The button shows how many hint(s) user has left. 
- Pressing the button multiple times for the same question won't decreases hints number 
- When out hint, no hint will be given.

Hint Hint Hint 

---

debug.log
src/components/Game/Game.js

Timer added for both Submit Button + Hint Button 

---

src/components/Game/Endgame.css
src/components/Game/Endgame.js
src/components/Game/Game.css
src/components/Game/Game.js
src/components/Game/Puzzle.js

Temp fix but still needs perm fix

We're in the endgame now bois

---

debug.log
package-lock.json
package.json

run `npm install --save-dev jest`

added Jest with configuration

---

package-lock.json
package.json
src/App.js
src/App.test.js
src/__snapshots__/App.test.js.snap
src/setupTests.js

https://medium.com/codeclan/testing-react-with-jest-and-enzyme-20505fec4675
run:
```npm install --save-dev enzyme enzyme-adapter-react-16 enzyme-to-json```
to install enzyme

Modified package.json and added some basic test

---

src/App.css
src/App.js
src/components/Footer/Footer.css
src/components/home.js

footer now at the bottom of viewport on all pages

---

debug.log
src/App.js
src/components/Game/Endgame.js
src/components/Game/Game.js
src/components/Game/Puzzle.js
src/components/Game/Timer.js

no reason, just want to test if I can fix my own problem lol

merge me pls 

---

debug.log
src/App.js
src/components/Game/Puzzle.js
src/components/Game/games.json
src/components/home.js

Also modify any file that use the old names

Changed Names of Variable in JSON file to follow 1 set of rule

---

debug.log
package-lock.json
package.json
src/components/Game/Answer.js
src/components/Game/Puzzle.js

Answer for Text didn't work properly 

---

src/components/Game/Answer.js
src/components/Game/Puzzle.js
src/components/Game/__test__/Puzzle.test.js

There's nothing that'll completely destroy the game lol. This can be pushed into master

just a bit more testing for puzzle.js

---

README.md
debug.log
src/components/Game/Game.css
src/components/Game/Game.js

Hot Fix for Image Displayed in Game List

---

package-lock.json
src/components/Game/Answer.js
src/components/Game/OrderQuestion/OrderQuestion.js
src/components/Game/OrderQuestion/orderQuestion.css
src/components/Game/Puzzle.js
src/components/Game/__test__/Game.test.js
src/components/Game/__test__/__snapshots__/Game.test.js.snap
src/components/Game/games.json

finished puppeteer testing of hero of angle game

---

amplify/backend/api/escaper/schema.graphql
debug.log
src/App.js
src/components/Game/Game.css
src/components/Game/Game.js
src/components/Game/Puzzle.js
src/components/Game/Question.js
src/components/Game/gamePanel.js
src/components/Navbar/Navbar.js
src/components/SideDrawerMenu/SideDrawerMenu.js
src/graphql/mutations.js
src/graphql/queries.js
src/graphql/schema.json
src/graphql/subscriptions.js

- Fix the sign-out button issue temporarily.
- Add "review" table.

Add "Review" Table

---

src/components/Game/Game.js
src/components/Game/Puzzle.js
src/components/Game/gamePanel.js
src/components/createGame/createGame.js
src/components/createGame/gameQuestions.js

Features added:
0. Fix ID of game exposed on the front end and can be manipulated.
1. Create Games Component (Once submit it will be written into DB).
- Create Questions Component (Submit 1 question at a time).
2. Fix Crashing when using Geo Location feature.
3. Add Reset button (for admins only), will reset the whole game (need refresh to see result).

New Features Added

---

src/App.js
src/components/Game/Game.js
src/graphql/subscriptions.js

- Subscription model is basically subscribe to every single item in the table.
- Changed to both backend + subscription.js to make sure user only subscribe to 1 game in the table they are in.

AWS Appsync Default Initialization is EVIL

---

debug.log
src/components/AdminDashboard/AdminDashboard.js
src/components/SideDrawerMenu/SideDrawerMenu.js

Fix William's code

---

src/components/Game/Game.js
src/components/Game/gamePanel.js
src/components/createGame/createGame.js
src/components/createGame/editGame.js
src/components/createGame/editQuestions.js

Edit Game + Questions can't remove question or re-order the questions.
Only can modify + add more questions in the end

Edit Game + Questions Added

---

debug.log
src/components/AdminDashboard/AdminDashboard.js

Fix William's code again SMH
Fix William's code again SMH
Fix William's code again SMH
Fix William's code again SMH
Fix William's code again SMH
Fix William's code again SMH

Fix William's code again SMH

---

src/components/Game/Game.js
src/components/Game/gamePanel.js

Now only show to username :admin,admin123,admin2

Emergency Fix for delete edit reset button
